services:
  lb:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: ["80:80"]
    depends_on: [app1, app2]

  app1:
    image: node:20-alpine
    command: sh -c "node -e \"require('http').createServer((req,res)=>{res.end('ok '+process.env.NAME)}).listen(8080)\""
    environment: [NAME=app1]

  app2:
    image: node:20-alpine
    command: sh -c "node -e \"require('http').createServer((req,res)=>{res.end('ok '+process.env.NAME)}).listen(8080)\""
    environment: [NAME=app2]